//! Wire protocol shared between the saber engine and every frontend
//! (TUI, macOS App, headless `saber exec`).
//!
//! This crate is the single source of truth: the committed JSON Schema
//! artifact (`schema/saber-protocol.json`, generated by the
//! `saber-export-schema` bin and enforced by test) feeds Swift/TS code
//! generation, and the session JSONL event schema lives here as well.
//!
//! Transport contract (spec §2.2): one bidirectional JSON-RPC 2.0 connection
//! over a Unix domain socket. Events are JSON-RPC notifications carrying a
//! monotonic sequence number; framing is newline-delimited JSON — no SSE.

pub mod event;
pub mod message;
pub mod session;

pub use event::{AssistantDelta, Event, EventMsg, TurnCompleteReason};
pub use message::{Block, Message, Role, Usage};
pub use session::{SessionEvent, SessionEventEnvelope};

/// Version of the saber engine<->frontend protocol (semver).
///
/// Frozen as `1.0.0` at M2; until then breaking changes stay within 0.x.
pub const PROTOCOL_VERSION: &str = "0.1.0";

/// Renders the committed-schema-artifact consistency check target: the exact
/// JSON document the `saber-export-schema` bin writes to
/// `schema/saber-protocol.json`. Shared by the bin and the tests so the
/// artifact and its snapshot can never drift apart.
pub fn schema_artifact_json() -> String {
    let defs = serde_json::json!({
        "Role": schemars::schema_for!(Role),
        "Message": schemars::schema_for!(Message),
        "Usage": schemars::schema_for!(Usage),
        "AssistantDelta": schemars::schema_for!(AssistantDelta),
        "EventMsg": schemars::schema_for!(EventMsg),
        "Event": schemars::schema_for!(Event),
        "SessionEvent": schemars::schema_for!(SessionEvent),
        "SessionEventEnvelope": schemars::schema_for!(SessionEventEnvelope),
    });
    let artifact = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "saber-protocol",
        "protocol_version": PROTOCOL_VERSION,
        "$defs": defs,
    });
    serde_json::to_string_pretty(&artifact).unwrap_or_else(|_| {
        // serde_json::Value serialization is infallible; unreachable by
        // construction.
        String::new()
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn protocol_version_is_semver_like() {
        let parts: Vec<&str> = PROTOCOL_VERSION.split('.').collect();
        assert_eq!(parts.len(), 3, "protocol version must be semver");
        assert!(
            parts.iter().all(|p| p.chars().all(|c| c.is_ascii_digit())),
            "protocol version components must be numeric until 1.0.0 freeze"
        );
    }

    #[test]
    fn committed_schema_artifact_is_current() {
        let committed = std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../schema/saber-protocol.json"
        ))
        .unwrap_or_else(|e| panic!("schema artifact missing, run `cargo run -p saber-protocol --bin saber-export-schema`: {e}"));
        assert_eq!(
            schema_artifact_json(),
            committed,
            "schema artifact is stale: regenerate with `cargo run -p saber-protocol --bin saber-export-schema` and commit it"
        );
    }

    #[test]
    fn schema_artifact_matches_snapshot() {
        insta::assert_snapshot!("saber_protocol_schema", schema_artifact_json());
    }
}
