//! Wire protocol shared between the saber engine and every frontend
//! (TUI, macOS App, headless `saber exec`).
//!
//! This crate is the single source of truth: the committed JSON Schema
//! artifact (`schema/saber-protocol.json`, generated by the
//! `saber-export-schema` bin and enforced by test) feeds Swift/TS code
//! generation, and the session JSONL event schema lives here as well.
//!
//! Transport contract (spec §2.2): one bidirectional JSON-RPC 2.0 connection
//! over a Unix domain socket. Events are JSON-RPC notifications carrying a
//! monotonic sequence number; framing is newline-delimited JSON — no SSE.

pub mod event;
pub mod message;
pub mod session;

pub use event::{AssistantDelta, Event, EventMsg, TurnCompleteReason};
pub use message::{Block, Message, Role, Usage};
pub use session::{SessionEvent, SessionEventEnvelope};

/// Version of the saber engine<->frontend protocol (semver).
///
/// Frozen as `1.0.0` at M2; until then breaking changes stay within 0.x.
pub const PROTOCOL_VERSION: &str = "0.1.0";

/// Renders the committed-schema-artifact consistency check target: the exact
/// JSON document the `saber-export-schema` bin writes to
/// `schema/saber-protocol.json`. Shared by the bin and the tests so the
/// artifact and its snapshot can never drift apart.
pub fn schema_artifact_json() -> String {
    let defs = serde_json::json!({
        "Role": schemars::schema_for!(Role),
        "Message": schemars::schema_for!(Message),
        "Usage": schemars::schema_for!(Usage),
        "AssistantDelta": schemars::schema_for!(AssistantDelta),
        "EventMsg": schemars::schema_for!(EventMsg),
        "Event": schemars::schema_for!(Event),
        "SessionEvent": schemars::schema_for!(SessionEvent),
        "SessionEventEnvelope": schemars::schema_for!(SessionEventEnvelope),
    });

    // schemars emits per-type sub-definitions as nested "$defs" whose $refs
    // use root paths ("#/$defs/X"). Hoist every nested definition to the
    // artifact root so all references resolve for strict resolvers and
    // quicktype-style codegen.
    let mut root_defs = serde_json::Map::new();
    if let Some(map) = defs.as_object() {
        for (name, schema) in map {
            root_defs.insert(name.clone(), schema.clone());
        }
    }
    collect_nested_defs(&defs, &mut root_defs);
    let mut defs_value = serde_json::Value::Object(root_defs);
    strip_nested_defs(&mut defs_value);

    let artifact = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "saber-protocol",
        "protocol_version": PROTOCOL_VERSION,
        "$defs": defs_value,
    });
    serde_json::to_string_pretty(&artifact).unwrap_or_else(|_| {
        // serde_json::Value serialization is infallible; unreachable by
        // construction.
        String::new()
    })
}

/// Recursively gathers every entry of every nested `$defs` object into `out`
/// (first definition of a name wins — duplicates are identical by
/// construction, all coming from the same Rust types).
fn collect_nested_defs(
    value: &serde_json::Value,
    out: &mut serde_json::Map<String, serde_json::Value>,
) {
    match value {
        serde_json::Value::Object(map) => {
            if let Some(serde_json::Value::Object(inner)) = map.get("$defs") {
                for (name, schema) in inner {
                    out.entry(name.clone()).or_insert_with(|| schema.clone());
                }
            }
            for child in map.values() {
                collect_nested_defs(child, out);
            }
        }
        serde_json::Value::Array(items) => {
            for child in items {
                collect_nested_defs(child, out);
            }
        }
        _ => {}
    }
}

/// Recursively removes every `$defs` key (callers hoist their contents to the
/// artifact root first, so nothing is lost).
fn strip_nested_defs(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            map.remove("$defs");
            for child in map.values_mut() {
                strip_nested_defs(child);
            }
        }
        serde_json::Value::Array(items) => {
            for child in items {
                strip_nested_defs(child);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn protocol_version_is_semver_like() {
        let parts: Vec<&str> = PROTOCOL_VERSION.split('.').collect();
        assert_eq!(parts.len(), 3, "protocol version must be semver");
        assert!(
            parts.iter().all(|p| p.chars().all(|c| c.is_ascii_digit())),
            "protocol version components must be numeric until 1.0.0 freeze"
        );
    }

    #[test]
    fn committed_schema_artifact_is_current() {
        let committed = std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../schema/saber-protocol.json"
        ))
        .unwrap_or_else(|e| panic!("schema artifact missing, run `cargo run -p saber-protocol --bin saber-export-schema`: {e}"));
        assert_eq!(
            schema_artifact_json(),
            committed,
            "schema artifact is stale: regenerate with `cargo run -p saber-protocol --bin saber-export-schema` and commit it"
        );
    }

    #[test]
    fn schema_artifact_matches_snapshot() {
        insta::assert_snapshot!("saber_protocol_schema", schema_artifact_json());
    }

    #[test]
    fn all_local_schema_refs_resolve() -> Result<(), serde_json::Error> {
        let artifact: serde_json::Value = serde_json::from_str(&schema_artifact_json())?;
        let root_defs: std::collections::BTreeSet<String> = artifact["$defs"]
            .as_object()
            .map(|defs| defs.keys().cloned().collect())
            .unwrap_or_default();
        let mut refs = Vec::new();
        collect_refs(&artifact, &mut refs);
        assert!(!refs.is_empty(), "expected at least one local $ref");
        for reference in refs {
            let name = reference
                .strip_prefix("#/$defs/")
                .unwrap_or(&reference)
                .to_owned();
            assert!(
                root_defs.contains(&name),
                "dangling local $ref {reference}: hoist the definition to the artifact root"
            );
        }
        assert!(
            root_defs.contains("Block") && root_defs.contains("TurnCompleteReason"),
            "definitions referenced across type boundaries must be hoisted to the root"
        );
        Ok(())
    }

    fn collect_refs(value: &serde_json::Value, out: &mut Vec<String>) {
        match value {
            serde_json::Value::Object(map) => {
                if let Some(serde_json::Value::String(reference)) = map.get("$ref") {
                    if reference.starts_with("#/$defs/") {
                        out.push(reference.clone());
                    }
                }
                for child in map.values() {
                    collect_refs(child, out);
                }
            }
            serde_json::Value::Array(items) => {
                for child in items {
                    collect_refs(child, out);
                }
            }
            _ => {}
        }
    }
}
